spring:
  datasource:
    flowable:
      username: root
      password: root
      url: jdbc:mysql://192.168.1.117:3306/flowable?useSSl=false&useCharset=utf8
      driver-class-name: com.mysql.jdbc.Driver

    master:
      username: root
      password: root
      url: jdbc:mysql://192.168.1.117:3306/demo?useSSl=false&useCharset=utf8
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /flowable-demo

flowable:
  idm:
    enabled: false
